# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Alex Earnshaw"
        tagline = "Principal Technical Writer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Ireland"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "00 353 (0)86 036 2096"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "alex.earnshaw@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "alex-earnshaw.netlify.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Markdown/Hugo (docs-as-code)"
        [[params.skills.list.items]]
        details = "Adobe FrameMaker/Madcap Flare"
        [[params.skills.list.items]]
        details = "SnagIt/Camtasia/Visio"
        [[params.skills.list.items]]
        details = "Git and Subversion"
        [[params.skills.list.items]]
        details = "DocBook XML/DITA XML"
        [[params.skills.list.items]]
        details = "Java/C/C++/SQL"
        [[params.skills.list.items]]
        details = "HTML/XML/CSS"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Remote working"
        [[params.skills.list.items]]
        details = "Quick learner"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Agile Scrum/Kanban"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Graduate Certificate in Technical Communication (1st class honours)"
        university = "University of Limerick"
        dates = "2003 - 2005"
        [[params.education.list]]
        degree = "BEng Electronic Engineering (2.1 honours)"
        university = "Dublin City University"
        dates = "1994 - 1998"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "I love automating. Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Principal Technical Writer"
        dates = "2013 - Present"
        company = "Axway"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "ScrumMaster"
        dates = "2016 - Present"
        company = "Axway"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Lead Technical Writer"
        dates = "2011 - 2013"
        company = "Openet"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
        [[params.experience.list.items]]
        details = "Leading and planning the technical writing work for a small team of technical writers."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Technical Writer (contract)"
        dates = "2007 - 2011"
        company = "Openet"
        details = "I was primarily involved in an OEM project in which two different brandings of the same user documentation suite were produced using FrameMaker."

        [[params.experience.list]]
        title = "Technical Writer"
        dates = "2004 - 2006"
        company = "Openet"
        details = "writing user manuals (Installation Guides, User Guides, API Guides) and online help for a suite of telecommunications software products built on a common framework. "

        [[params.experience.list]]
        title = "Software Design Engineer"
        dates = "2001 - 2004"
        company = "Openet"
        details = "Telecommunications software design and development using Java."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2000 - 2001"
        company = "Aran Technologies"
        details = "Telecommunications research, software design and development using C++."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "1999 - 2000"
        company = "Altion"
        details = "Support and maintenance of network management software."









    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Axway-Open-Docs"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Flarestrap Doc Portal"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Migration projects"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"





